### ISSUE TITLE
static page似乎会有问题

### ISSUE THREAD

**Issue by mjc0608** [ty96/toxni-theme#1]
如上，static page无法被翻译为静态页，跳转出500错误：[page.hbs] pageination data is not an object or an funciton

**Comment by ty96** [comment]
我这边 [Ghost 10.11.3] 没有问题，{{pageination}} 这个组件貌似是官方的，你多发几篇文章分页试试？

**Comment by mjc0608** [comment]
我这里似乎是.4，以及直接上传主题的时候报了个错，不知道是不是我这里的问题
